language: cpp
dist: bionic
sudo: required

before_install:
    - eval "${MATRIX_EVAL}"

install:
  # Install conan
  - sudo -E pip install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build ${LIBVERSION}
  - cmake ..
  - cmake --build .
  - ./bin/test_hello

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         - LIBVERSION="-s compiler.libcxx=libstdc++11"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
      env:
         - MATRIX_EVAL="CC=clang && CXX=clang++"
         - LIBVERSION="-s compiler.libcxx=libstdc++11"
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
