language: cpp
sudo: required

before_install:
    - eval "${MATRIX_EVAL}"

install:
  # Install conan
  - sudo -E pip install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

  - |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    pip install --user -q conan
  else
    # Install conan
    sudo -E pip install conan
  fi
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build
  - cmake ..
  - cmake --build .
  - ./bin/test_hello

matrix:
  include:
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - gcc-5
    #         - g++-5
    #   env:
    #      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - gcc-6
    #         - g++-6
    #   env:
    #      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-trusty-6.0
    #       packages:
    #         - clang-6.0
    #   env:
    #      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    # - os: linux
    #   dist: bionic
    #   addons:
    #     apt:
    #       sources:
    #         - llvm-5.0-dev
    #       packages:
    #         - clang-5
    #   env:
    #      - MATRIX_EVAL="CC=clang-5 && CXX=clang++-5"
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
